### ISSUE TITLE
Plugin Doesn't Work on Cordova 2.2.0

### ISSUE THREAD

**Issue by orafaelfragoso** [litehelpers/Cordova-ios-UniqueDeviceId#1]
Can someone update it to Cordova 2.2.0? I'm stucked here.

**Comment by brody2consult** [comment]
> Can someone update it to Cordova 2.2.0? I'm stucked here.

Happy you tried this plugin. I will take a look later this week.

**Comment by orafaelfragoso** [comment]
If you could help me now, my boss is kicking my ass right now to send an update.
Thanks!

**Comment by brody2consult** [comment]
I still have to work a few more hours for my day job, then I try to
fix it. Chris

**Comment by brody2consult** [comment]
I updated the plugin to build on Cordova 2.1, should build on Cordova 2.2, please report whether or not it works for you.

**Comment by scottriggle** [comment]
I see this plugin uses part of the devices mac address? Know of a plugin that Will return the mac address? I've been looking for several months. Thanks !!

**Comment by orafaelfragoso** [comment]
+1
